#:kivy 1.0
#:import kivy kivy
#:import win kivy.core.window

<Image>:
    # fill the entire screen with the background image
    allow_stretch: True
    keep_ratio: False
    pos_hint: {'center_x':0.5}

#<Button>:
#	background_normal: './images/vkeyboard_key_normal.png'
#	background_down: './images/vkeyboard_key_down.png'
	
<AccordionItem>:
	background_normal: './images/vkeyboard_key_normal.png'
	background_selected: './images/vkeyboard_key_down.png'
